### ISSUE TITLE
[FEATURE REQUEST]: API ENDPOINTS - Subtask 1

### ISSUE THREAD

**Issue by ekpono** [hngi/fury-backend-php#11]
This issue is to create API endpoints for:

 1. Endpoint for creating a new Meeting POST /meetings.

**Comment by horlathunbhosun** [comment]
Great one But you need to communicate with  other services like auth, planner and Employee record to achieve that??

**Comment by horlathunbhosun** [comment]
I will inform you once we have one of these microservice we start work

**Comment by dave-ok** [comment]
Feature completed in PR #26
