### ISSUE TITLE
[FEATURE REQUEST]: Add Authentication

### ISSUE THREAD

**Issue by horpschenzy** [hngi/fury-backend-php#4]
**Is your feature request related to a problem? Please describe.**
A simple authentication system is needed for the system.

**Describe the solution you'd like**
Email and password will be requested fo authentication

**Describe alternatives you've considered**
No alternatives.

**Additional context**
no additional context

**Comment by AyoAyomide** [comment]
About authintication I can work with that and add protection and password hashing

**Comment by horlathunbhosun** [comment]
I think the nodejs backend team will work on that...

**Comment by AyoAyomide** [comment]
Oh it was tagged under php

**Comment by horlathunbhosun** [comment]
I will remove it now

**Comment by AyoAyomide** [comment]
Okay

**Comment by horlathunbhosun** [comment]
Please @horpschenzy  close this feature
